http://localhost:3000/users


###
POST http://localhost:3000/users/register
Content-Type: application/json

    { 
        "firstName": "Johnny",
        "lastName": "Tejada",
        "age": "21",
        "height": "6ft 2in",
        "weight": "195",
        "handle": "johnnyfco",
        "pic": "https://www.igeeksblog.com/wp-content/uploads/2021/03/Can-you-check-who-viewed-your-Instagram-profile.jpg",
        "password": "yo",
        "isAdmin": true,
        "emails": [
            "tejadaj6@newpaltz.edu"
        ],
        "following": [ 
            { 
                "handle": "vp", "isApproved": true 
            }
        ]
    }

###
POST http://localhost:3000/users/register
Content-Type: application/json

    { 
        "firstName": "Kamala",
        "lastName": "Harris",
        "age": "20",
        "height": "5ft 4in",
        "weight": "135",
        "handle": "vp",
        "pic": "https://www.finetoshine.com/wp-content/uploads/2020/07/instagram-profile-picture-aesthetic.jpg",
        "password": "Her",
        "isAdmin": true,
        "emails": [
            "vp@wh.com"
        ],
        "following": [ 
            { 
                "handle": "johnnyfco", "isApproved": true 
            }
        ]
    }

###
POST http://localhost:3000/users/login
Content-Type: application/json

    { 
        "handle": "johnnyfco",
        "password": "yo"
    }

###
POST http://localhost:3000/users/seed


####################################################
http://localhost:3000/posts

###
POST http://localhost:3000/posts
Content-Type: application/json

{
    "src": "https://www.eatthis.com/wp-content/uploads/sites/4/2020/01/man-weight-lifting-training-workout-gym.jpg?quality=82&strip=1&resize=640%2C360",
    "alt": "Placeholder image",
    "caption": "Lorem Ipsom",
    "user_handle": "johnnyfco",
    "category": "Back/Biceps",
    "isPublic": true,
}

###
POST http://localhost:3000/posts
Content-Type: application/json

{
    "src": "https://post.healthline.com/wp-content/uploads/2019/10/Female_Male_Rope_Workout_1200x628-facebook.jpg",
    "alt": "Placeholder image",
    "caption": "jdkjfkjfkf",
    "user_handle": "johnnyfco",
    "category": "Chest/Triceps",
    "isPublic": true,
}

###
POST http://localhost:3000/posts
Content-Type: application/json

{
    "src": "https://post.healthline.com/wp-content/uploads/2019/10/Female_Male_Rope_Workout_1200x628-facebook.jpg",
    "alt": "Placeholder image",
    "caption": "kgjjfhfkfhfhgfhghggh",
    "user_handle": "vp",
    "category": "Legs",
    "isPublic": true,
}

###
http://localhost:3000/posts/wall/johnnyfco

###
http://localhost:3000/posts/feed/johnnyfco

###
http://localhost:3000/posts/search?q=never

###
POST http://localhost:3000/posts/seed

####################################################
http://localhost:3000/goals

###
POST http://localhost:3000/goals
Content-Type: application/json

{
    "mon": "Incline Bench, Flat Bench, Overhead Press, DB flat bench, DB incline press",
    "tues": "Lats Pull down, Seated Rows, Pull ups, Bent over rows, Bicep curls, Shoulder raise",
    "weds": "Squats, Seated quads push, Hamstring pulls",
    "thurs": "Incline Bench, Flat Bench, Overhead Press, DB flat bench, DB incline press",
    "fri": "Lats Pull down, Seated Rows, Pull ups, Bent over rows, Bicep curls, Shoulder raise",
    "sat": "Rest",
    "sun": "Rest",
    "categoryM": "Chest/Triceps",
    "categoryT": "Back/Biceps",
    "categoryW": "Legs",
    "categoryTH": "Chest/Triceps",
    "categoryF": "Back/Biceps",
    "categorySA": "Rest",
    "categoryS": "Rest",
    "user_handle": "johnnyfco",
    "isPublic": false,
}

###
POST http://localhost:3000/goals/seed

###
http://localhost:3000/goals/wall/johnnyfco

####################################################
http://localhost:3000/track

###
POST http://localhost:3000/track
Content-Type: application/json

{
    "cBench": "225",
    "cIBench": "185",
    "cOPress": "95",
    "cDeadlift": "",
    "gBench": "",
    "gIncline": "225",
    "gOPress": "",
    "gDeadlift": "",
    "cBSquats": "225",
    "cSSquats": "40",
    "cGBridges": "",
    "gBSquats": "",
    "gSSquats": "50",
    "gGBridges": "",
    "cMiles": "",
    "gMiles": "",
    "user_handle": "johnnyfco",
    "isPublic": false,
}

###
POST http://localhost:3000/track/seed

###
http://localhost:3000/track/wall/johnnyfco